### ISSUE TITLE
Add .terraform-docs.yaml for all terraform repos

### ISSUE THREAD

**Issue by jamiezieziula** [PrefectHQ/prefect-recipes#43]
```
formatter: markdown
header-from: .header.md
settings:
  anchor: true
  color: true
  default: true
  escape: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true

sort:
  enabled: true
  by: required

output:
  file: README.md
  mode: replace
```
